### ISSUE TITLE
Hook up a Ruby style checker?

### ISSUE THREAD

**Issue by maxlinc** [WinRb/WinRM#105]
I noticed a lot of the code doesn't follow the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). Not following whitespace rules is a pet peeve of mine - because my IDE to automatically fix whitespace (at the request of other Ruby projects), and those autofixes show up when I commit.

There are a few useful projects you could consider using:

## Rubocop

https://github.com/bbatsov/rubocop

Rubocop is a popular Ruby stylechecker. It has a few useful options:

- `--autofix` does just that. It's useful if you want to do a one-time mass cleanup. I ran it locally and it detected 1470 offenses but was able to fix 1201 of them.
- `--auto-gen-config`: "Generate a configuration file acting as a TODO list". That way your current style violations are ignored, but you can start using Rubocop to prevent violations.

Some examples:
```yaml
# Offense count: 11
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 180
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 189
```

So rubocop will only complain if you introduce a new type of violation, or an even more egregious offense (like a 190 character line).

### HoundCI

https://houndci.com/

I just came across this recently, but I like the idea. Here's an explanation from their FAQ:

> No, and we don't recommend doing so. Our rule is "Don't rewrite existing code to follow the style guide." See the [thoughtbot style guide](https://github.com/thoughtbot/guides#guides).
> 
> It can be dangerous to re-write a lot of code for just style reasons. It can introduce functional regressions, which are a higher-level concern than style.
> 
> We believe the right approach is to convert a codebase over time, one pull request at a time, to conform to a style guide. Only focus on style in diffs and make smaller changes that ideally have tests associated with them.
>
> If you'd still like to analyze your whole repo, try using Rubocop locally.

This is also nice, because when people use Rubocop it's often setup to fail the CI build. CI builds often fail when a new Rubocop release comes out and adds additional rules - even though Rubocop (older version) passed locally.

Hound just adds comments, so you'll still see that a build is "good to merge" if all the tests pass, but the PR will contain suggestions for cleaning up the code.

### pre-commit or other generic tools

http://pre-commit.com/

This is another interesting project if you just want some general things like whitespace cleanup or [powershell linting](http://stackoverflow.com/questions/2987176/is-there-a-powershell-code-formatter-pretty-printer), rather than a ruby specific stylechecker.

But it's written in python and the setup isn't as simple as Rubocop or Hound for Ruby projects.

**Comment by sneal** [comment]
Fixed by #118.

I ended up going with RuboCop mainly because I'm already familiar with it and the code base isn't that large.
