### ISSUE TITLE
File uploads break on win7/2008R2

### ISSUE THREAD

**Issue by mwrock** [WinRb/WinRM#112]
One thing we found in test-kitchen was that win7/server 2008R2, by default, imposes a limit of 15 commands per session captured by the `maxConcurrentOperationsPerUser` setting which defaults to 1500 in win8/2012 and higher.

In Test-kitchen I get around this by counting the operations and "resetting" the connecion once the threshold is reached. A better approach would be to catch the exact exception and then reset the connection because its possible to set the limit to any arbitrary number. That approach is not possible in winrm v1.2 since there is no visibility into the 500 responses which has since been fixed in 1.3. Further, there is no way to remotely "sniff" the setting since those properties cannot be read in a remote session. You would have to break out into a scheduled task which would probably be overkill.

**Comment by sneal** [comment]
Moved the issue to the new winrm-fs repo
