### ISSUE TITLE
WinRM 1.3 release?

### ISSUE THREAD

**Issue by maxlinc** [WinRb/WinRM#121]
I just wanted to inquire about when 1.3 might drop. I've got a few PRs in vagrant and vagrant-rackspace that can't be merged until then.

I can help if you need a hand closing out a few issues before it's ready for a release, but the only remaining issue I see in the 1.3 milestone is #59. I haven't tried to fix it, but if the fix is as simple as the original #84 solution then it looks pretty easy.

Do you need help with anything else?

**Comment by sneal** [comment]
Basically #59 and a basic regression pass over the different transport types, including Kerberos. Any help would be appreciated.

**Comment by maxlinc** [comment]
If you create issues or tag existing issues where you could use some help with the 1.3 milestone then I'll take a look and see where I could jump in.

**Comment by sneal** [comment]
1.3 has been released.
