### ISSUE TITLE
rwinrm won't take .'s in username

### ISSUE THREAD

**Issue by stonith** [WinRb/WinRM#124]
https://github.com/WinRb/WinRM/blob/master/bin/rwinrm#L35

first.last@host doesn't work.

**Comment by sneal** [comment]
Bummer, that's a pretty common character for user names too.

From [Creating User and Group Accounts](https://msdn.microsoft.com/en-us/library/bb726984.aspx)
```
Logon names can't contain certain characters. Invalid characters are
" / \ [ ] : ; | = , + * ? < >
Logon names can contain all other special characters, including spaces, periods, dashes, and underscores. But it's generally not a good idea to use spaces in account names.
```

**Comment by sneal** [comment]
Fixed
