### ISSUE TITLE
Output Japanese character is garbled

### ISSUE THREAD

**Issue by stknohg** [WinRb/WinRM#125]
When I use this library and get message from stdout/stderr, Japanese character in the message is garbled.  
My Environment and Sample code is following.

My Environment

 * OS: Windows 8.1 Enterprise 64bit Evaluation (Lang=JP)
 * Ruby: 2.1.5 (Installed from [RubyInstaller](http://rubyinstaller.org/))
 * WinRM: 1.3.0

Sample Code (connect localy and get Write-Output message.)
```ruby
# encoding: utf-8
require 'winrm'

$script = "Write-Output '日本語Test'"

endpoint = 'http://127.0.0.1:5985/wsman'
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => "Administrator", :pass => "Password", :basic_auth_only => true)
winrm.powershell($script) do |stdout, stderr|
  print stdout
  print stderr
end
```

Result (garbled)
```
???Test

```

Expected
```
日本語Test

```  

In my investigation,I found that this probrem was solved when I modify `WinRMWebService.run_cmd` method and set codepage 932(=Japanese default codepage).

winrm_service.rb(orig)

```ruby
    def run_cmd(command, arguments = [], &block)
      command_output = nil
      open_shell do |shell_id|
        run_command(shell_id, command, arguments) do |command_id|
          command_output = get_command_output(shell_id, command_id, &block)
        end
      end
      command_output
    end
```

winrm_service.rb(set codepage 932)

```ruby
    def run_cmd(command, arguments = [], &block)
      command_output = nil
      # set codepage 932
      open_shell({:codepage => 932}) do |shell_id|
        run_command(shell_id, command, arguments) do |command_id|
          command_output = get_command_output(shell_id, command_id, &block)
        end
      end
      command_output
    end
```

Result when codepage is 932
```
日本語Test

```

The problem was solved, but there is no way to change codepage from the outside of `WinRMWebService` class.

**Comment by stknohg** [comment]
In addition, I found that Remote default codepage was used when not setting `WINRS_CODEPAGE` option.

SOAP Message when 'WINRS_CODEPAGE' codepage is used.
```xml
  <env:Header>
    <a:To>http://127.0.0.1:5985/wsman</a:To>
    <a:ReplyTo>
      <a:Address mustUnderstand='true'>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>
    </a:ReplyTo>
    <w:MaxEnvelopeSize mustUnderstand='true'>153600</w:MaxEnvelopeSize>
    <a:MessageID>uuid:1C6295E2-8CB1-4205-8408-D1939B0C8D1A</a:MessageID>
    <w:Locale xml:lang='en-US' mustUnderstand='false'/>
    <p:DataLocale xml:lang='en-US' mustUnderstand='false'/>
    <w:OperationTimeout>PT60S</w:OperationTimeout>
    <w:ResourceURI mustUnderstand='true'>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>
    <a:Action mustUnderstand='true'>http://schemas.xmlsoap.org/ws/2004/09/transfer/Create</a:Action>
    <w:OptionSet>
      <w:Option Name='WINRS_NOPROFILE'>FALSE</w:Option>
      <w:Option Name='WINRS_CODEPAGE'>437</w:Option>
    </w:OptionSet>
  </env:Header>
  <env:Body>
    <rsp:Shell>
      <rsp:InputStreams>stdin</rsp:InputStreams>
      <rsp:OutputStreams>stdout stderr</rsp:OutputStreams>
    </rsp:Shell>
  </env:Body>
</env:Envelope>
```

SOAP Message when remote default codepage (=932) is used.
```xml
  <env:Header>
    <a:To>http://127.0.0.1:5985/wsman</a:To>
    <a:ReplyTo>
      <a:Address mustUnderstand='true'>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>
    </a:ReplyTo>
    <w:MaxEnvelopeSize mustUnderstand='true'>153600</w:MaxEnvelopeSize>
    <a:MessageID>uuid:1C6295E2-8CB1-4205-8408-D1939B0C8D1A</a:MessageID>
    <w:Locale xml:lang='en-US' mustUnderstand='false'/>
    <p:DataLocale xml:lang='en-US' mustUnderstand='false'/>
    <w:OperationTimeout>PT60S</w:OperationTimeout>
    <w:ResourceURI mustUnderstand='true'>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>
    <a:Action mustUnderstand='true'>http://schemas.xmlsoap.org/ws/2004/09/transfer/Create</a:Action>
    <w:OptionSet>
      <w:Option Name='WINRS_NOPROFILE'>FALSE</w:Option>
    </w:OptionSet>
  </env:Header>
  <env:Body>
    <rsp:Shell>
      <rsp:InputStreams>stdin</rsp:InputStreams>
      <rsp:OutputStreams>stdout stderr</rsp:OutputStreams>
    </rsp:Shell>
  </env:Body>
</env:Envelope>
```

**Comment by sneal** [comment]
Are you saying that we shouldn't [add WINRS_CODEPAGE](https://github.com/WinRb/WinRM/blob/b09965c9332be8ec27480a599c283ff4cd34b396/lib/winrm/winrm_service.rb#L102) to every open_shell SOAP message by default (since it defaults to 437)? Only add it if the caller explicitly specifies a codepage.

And if so, does that fix your issue?

**Comment by stknohg** [comment]
Yes. I think so.

if so, my issue will be fixed.

**Comment by Mazwak** [comment]
I don't think it will work for everyone. Unsetting the WINRS_CODEPAGE will only fix the problem when the client and the server use the same encoding.

The problem :
By default, the winrs response uses whatever codepage is the default on the server. As soon as the client uses a different encoding, it will most likely break.
By forcing CP 437, you basically restrict everything to latin1 (8859-1), more or less. That's why stknohg gets '?'. Note here that it is the character '?', not an encoding problem. The server replaced the invalid character with a '?' before replying to the client.
I think a solution for powershell would be to use CP 65001 (UTF-8) which is available on all windows, afaik.

The response from the server would then need to be correctly set to "utf-8", as it is encoded as ASCII-8BIT after the base64 decode.
After that, maybe encode to local encoding, or leave it to the user.

After changing the winrs_codepage, you can try :

```ruby
require 'winrm'

endpoint = 'http://auie:5985/wsman'
winrm = WinRM::WinRMWebService.new(endpoint)

script = "Write-Output 'éàçñ日本語'"

winrm.powershell(script) do |stdout, stderr|
  puts stdout
  puts stdout.force_encoding("CP65001").encode("utf-8")
end
```

Now that fixes the powershell issue.

However, "run_cmd" is another beast. I don't think there is a solution. You can take a look at http://stackoverflow.com/a/17177904 . Briefly, cmd is encoding agnostic and will pass the output as is, which can be anything, as the command run can output whatever it wants, more or less.

Maybe force user to specify which encoding the output will be, or raise an error.

**Comment by stknohg** [comment]
Thanks @Mazwak, I tried your code,

```ruby
require 'winrm'

endpoint = 'http://auie:5985/wsman'
winrm = WinRM::WinRMWebService.new(endpoint)

script = "Write-Output 'éàçñ日本語'"

winrm.powershell(script) do |stdout, stderr|
  puts stdout.force_encoding("CP65001").encode("utf-8")
end
```

Text Result is following
```
ｅ・???
```

Binary Value is following. (I think it was encoded Little Endian UCS-2)

```
FF FE 45 FF FB 30 3F 00 3F 00 3F 00
```

Your mention,

>By forcing CP 437, you basically restrict everything to latin1 (8859-1), more or less. That's why stknohg gets '?'. Note here that it is the character '?', not an encoding problem. The server replaced the invalid character with a '?' before replying to the client.

I think you are correct.  
The server(CP437) can't recognize Japanese,so `日本語` changed to `???(3F 00 3F 00 3F 00)` at "Remote" side. (Sorry, I don't know why latin-1 words changed `45 FF FB 30`. )  
But, Your code is forcing CP65001 at "Local" side.

In addition, Changing "Remote" Server codepage to CP65001, The result is more worse.  
Text result
```
 ﾃｩﾃﾃｧﾃｱ譌･譛ｬ隱・
``` 
Binary result
```
FF FE 83 FF 69 FF 83 FF F0 F8 83 FF 67 FF 83 FF 71 FF 4C 8B 65 FF 5B 8B 6C FF B1 96 FB 30
```

In most cases, Using CP65001 in Japanese Windows Environment gets very terrible result.

and

>I don't think it will work for everyone. Unsetting the WINRS_CODEPAGE will only fix the problem when the client and the server use the same encoding.

I don't think so.  
I think Unsetting the WINRS_CODEPAGE will fix the problem between convertible encoding.not only the same.

>By default, the winrs response uses whatever codepage is the default on the server. As soon as the client uses a different encoding, it will most likely break.

I agree this point.  
If user using different encoding, user should change codepage. 

I think unsetting codepage is default, setting value only when necessary is good way.

**Comment by Mazwak** [comment]
Did you try the code after changing the line 99 in winrm_service.rb ?

```
- codepage = shell_opts.has_key?(:codepage) ? shell_opts[:codepage] : 437
+ codepage = shell_opts.has_key?(:codepage) ? shell_opts[:codepage] : 65001
```

Also, is your script encoding utf-8 or shift-JIS ?

I tried again without setting the codepage, and I confirm the server uses its default codepage, not the client one. In my case, UTF-8 on client, and CP850 on server. So the japanese characters get replaced.

I don't know if the encoding is specified in the server response. If it is, it would be nice to change the encoding from ascii-8bit to the real encoding. If it is not, a big warning in the README would be nice to remind the user he has to set the proper encoding on the result.

It would also be nice to be able to specify encoding in run_powershell, as it is only available in open_shell right now.

**Comment by stknohg** [comment]
My script encoding is UTF-8.
I tried after changing winrm_service.rb codepage 65001.

```ruby
require 'winrm'

endpoint = 'http://auie:5985/wsman'
winrm = WinRM::WinRMWebService.new(endpoint)

script = "Write-Output 'éàçñ日本語'"

winrm.powershell(script) do |stdout, stderr|
  print stdout
end
```

The result is following, output is correct.
```
éàçñ日本語
```
Thank you for your advice.

**Comment by sneal** [comment]
Closing as #130 should fix this. If not, we can re-open.
