### ISSUE TITLE
support domain user authentication

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/WinRM#126]
I have a remote ldap user that is a member of the domain and is a member of the Local Administrator's group.

Would it be possible to use something like ...

```ruby
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => 'MYDOMAIN\user', :pass => 'MYPASS', :basic_auth_only => true)
```

**Comment by sneal** [comment]
You can use domain creds, although I don't think it'll work with basic auth.

**Comment by lmayorga1980** [comment]
Uhmmm, So it does not authenticate domain users I guess. Is there a way to
use Kerberos without the MIT client files?

**Comment by sneal** [comment]
You can you Kerberos, but you don't need to (Kerberos != NTLM). Try this:

```ruby
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => 'MYDOMAIN\user', :pass => 'MYPASS', :basic_auth_only => false)
```

**Comment by mwrock** [comment]
I have had luck with:

```
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => 'MYDOMAIN\user', :pass => 'MYPASS', :disable_sspi => true)
```

Note the use of `disable_sspi` instead of `basic_auth_only`
