### ISSUE TITLE
Use of sub! in run_command results in spurious capture/replacement of \& sequences.

### ISSUE THREAD

**Issue by ksubrama** [WinRb/WinRM#131]
https://github.com/WinRb/WinRM/blob/ccafbf020bc887e63ed2f31f956adacc20e3fa99/lib/winrm/winrm_service.rb#L122

run_command performs ```xml.sub!(escaped_cmd, escaped_cmd.gsub(/&#39;/, "'"))``` to work around a framework issue from https://github.com/WinRb/WinRM/pull/73 but sub looks for backreferences in the replacement string.  Doing Regexp.escape on the replacement string should correct this but this seems like going around one's head to touch one's nose but I can't think of a simpler way to do it.

A real-life example of this occurring is when you pass "\" anywhere in your command because it gets escaped to &quot;\&quot; which causes \& to be captured.

**Comment by mwrock** [comment]
Hey @ksubrama do you think you could add a test for this in https://github.com/WinRb/WinRM/blob/master/spec/cmd_spec.rb ? In addition to defending from regressions it would also better illustrate your example above. Thanks!

**Comment by ksubrama** [comment]
Done!  Let me know if this is enough.  I actually found an issue with my initial implementation in the process.  The current version passes all tests.

**Comment by ksubrama** [comment]
@mwrock =^.^=

**Comment by sneal** [comment]
Merged the PR, thanks guys.
