### ISSUE TITLE
REPL fails when using a host with a dash in its name

### ISSUE THREAD

**Issue by nicolasbrechet** [WinRb/WinRM#138]
Hi,

Most of my hosts have dashes in the hostname, for example they're named "company-servicename-01", "company-servicename-02", ...

Using `rwinrm` fails:
```
$ rwinrm my_login@company-service-01.domain.tld
Password:
getaddrinfo: nodename nor servname provided, or not known (http://company:5985)
```

However using an alias without dashes works perfectly...

Changing part of the regexp from (?<host>[a-z0-9\.]+) to (?<host>[a-z0-9\.\$ -]+) should work with the dashes.

Is it something you would consider modifying ?

**Comment by sneal** [comment]
Fixed by #139
