### ISSUE TITLE
winrm is timing out even for a bigger timeout

### ISSUE THREAD

**Issue by puneetloya** [WinRb/WinRM#146]
ar/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:64:in `raise_if_wsman_fault': [WSMAN ERROR CODE: 2150858843]: <f:WSManFault Code='2150858843' Machine='10.0.201.153' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The request for the Windows Remote Shell with ShellId 4FF93B86-AE92-407B-ACBB-A845F327664B failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. </f:Message></f:WSManFault> (WinRM::WinRMWSManFault)
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/http/transport.rb:50:in `send_request'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:430:in `send_message'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:288:in `close_shell'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:133:in `ensure in open_shell'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:133:in `open_shell'
	from /var/lib/gems/1.9.1/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:299:in `run_cmd'
	from run_tests.rb:12:in `<main>'

**Comment by sneal** [comment]
Do you have a repro for this?

**Comment by puneetloya** [comment]
Yep... I am running this script

```

**Comment by puneetloya** [comment]
require 'winrm'
endpoint = "192.x.x.x"
opts = {}
opts[:user] = 'xyzz'
opts[:pass] = 'abc'
winrm = WinRM::WinRMWebService.new(endpoint,:plaintext,opts)
winrm.set_timeout(7200)
winrm.cmd('C:\\run_tests.bat') do |stdout, stderr|
  STDOUT.print stdout
  STDERR.print stderr
end
```

**Comment by sneal** [comment]
How long does `run_tests.bat` take to finish if you run it locally without using WinRM?

**Comment by puneetloya** [comment]
sorry for closing it.. if you can see I am applying a huge timeout, even then it crashes by 21 mins, sometimes 19 mins.. this is the winrm config from the windows system

MaxEnvelopeSizekb = 500
MaxTimeoutms = 18000000
MaxBatchItems = 32000
MaxProviderRequests = 4294967295
Client
    NetworkDelayms = 5000
    URLPrefix = wsman
    AllowUnencrypted = false
    Auth
        Basic = true
        Digest = true
        Kerberos = true
        Negotiate = true
        Certificate = true
        CredSSP = false
    DefaultPorts
        HTTP = 5985
        HTTPS = 5986
    TrustedHosts
Service
    RootSDDL = XYZ
    MaxConcurrentOperations = 4294967295
    MaxConcurrentOperationsPerUser = 1500
    EnumerationTimeoutms = 240000
    MaxConnections = 300
    MaxPacketRetrievalTimeSeconds = 120
    AllowUnencrypted = true
    Auth
        Basic = true
        Kerberos = true
        Negotiate = true
        Certificate = false
        CredSSP = false
        CbtHardeningLevel = Relaxed
    DefaultPorts
        HTTP = 5985
        HTTPS = 5986
    IPv4Filter = *
    IPv6Filter = *
    EnableCompatibilityHttpListener = false
    EnableCompatibilityHttpsListener = false
    CertificateThumbprint
    AllowRemoteAccess = true
Winrs
    AllowRemoteShellAccess = true
    IdleTimeout = 7200000
    MaxConcurrentUsers = 10
    MaxShellRunTime = 2147483647
    MaxProcessesPerShell = 25
    MaxMemoryPerShellMB = 300
    MaxShellsPerUser = 30

**Comment by puneetloya** [comment]
they run for about 41 mins..

**Comment by sneal** [comment]
@puneetloya I can't reproduce this problem. I created a batch file on my windows host that pings localhost 1800 times, i.e. it should run for about 30m. I set the winrm timeout to the same you have.

winrm code:
```ruby
describe 'field report', integration: true do
  before(:all) do
    @winrm = winrm_connection
  end

  it 'should not timeout' do
    @winrm.set_timeout(7200)
    @winrm.cmd('C:\run_tests.bat') do |stdout, stderr|
      STDOUT.print stdout
      STDERR.print stderr
    end
  end
end
```
run_tests.bat
```
ping localhost -n 1800
```
output
```
...
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1800, Received = 1800, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
  should not timeout

Finished in 29 minutes 59 seconds (files took 0.16548 seconds to load)
```
Which WinRM version are you using?

**Comment by sneal** [comment]
Closing for lack of response and I can't reproduce this. We can re-open later if needed.

**Comment by jonescomas** [comment]
Same issue here: pywinrm version 0.2.2

**Comment by mwrock** [comment]
@jonescomas this is actually the ruby winrm gem repo. You probably want to submit an issue or search for info at https://github.com/diyan/pywinrm
