### ISSUE TITLE
Possible to authenticate as a different domain user?

### ISSUE THREAD

**Issue by adamjreilly** [WinRb/WinRM#15]
Not sure if this is obvious or not, but I've had problems trying to  run commands as a different user on our domain.  A little background:
- I'm logged into my Linux machine via Likewise-open5 as "ourDomain\me"
- I'd like to be able to run remote commands as 'ourDomain\dummy-user" on a remote Windows box
- login environment is pretty important as we'll be running bundler, ruby and Git commands, which all seem pretty tied to a user's environment
- I'm able to supply the username and password of a local administrator on the Windows box and run commands under that environment using the following:
  
  ep = 'remoteHost01'
  WinRM::WinRMWebService.new("http://#{ep}:5985/wsman", :ssl, :user => 'localAdmin', :pass => 'laPass', :basic_auth_only => true)

Everything works if I use credentials for the local admin, however, I can't specify different credentials for a user on the domain.  If I try kerberos authentication, it ignores any credentials and logs me in as 'ourDomain\me'  I'm assuming the Gem is pulling straight from wherever Likewise is caching my identity.  

Is what I'm looking to do possible?  Let me know if there are any other details I can provide.

**Comment by davalente** [comment]
Hi,

Any update on this issue?
How can I autenticate with user/password from a linux with kerberos?
The ideia is give the user, password, domain, real to autenticate.

Regards
