### ISSUE TITLE
Missing end tag for 'META' (got "HEAD")

### ISSUE THREAD

**Issue by xsannyx** [WinRb/WinRM#153]
I connect to my endpoint:
```
winrm = WinRM::WinRMWebService.new(endpoint, :ssl, :user => myuser, :pass => mypass, :ca_trust_path => mycert_path, :basic_auth_only => true)
```

And when I run:
```
winrm.cmd('ipconfig /all') do |stdout, stderr|
  STDOUT.print stdout
  STDERR.print stderr
end
```
I get this error message:
```
WinRM::WinRMHTTPTransportError: Unable to parse WinRM response: Missing end tag for 'META' (got "HEAD")
Line: 3
Position: 208
Last 80 unconsumed characters:
 (404).
```

I tried connecting to my endpoint via powershell from a windows machine and it worked fine, so I think the problem is in my ruby configuration..

UPDATE:

I am using azure for this.

I also tried connecting via plaintext and got the same error.

I was able to replicate this error on another machine.

**Comment by mwrock** [comment]
What windows version are you connecting to? Is there a proxy server you are going through?

**Comment by xsannyx** [comment]
No proxy server.
Microsoft Windows Server 2012 R2 Datacenter (version 6.3.9600)

**Comment by sneal** [comment]
@xsannyx What's the endpoint URL? It looks like you're getting back an HTML response instead of a SOAP response from the WinRM service.

**Comment by mwrock** [comment]
yeah I'd be willing to bet this is a port issue. Depending on whether or not you have more than one VM attached to a single azure service, Azure will NAT a non 5986 external port to the default winrm HTTPS (5986) port on the box. 

I usually use `Get-AzureWinRMUri` to find that out using the azure powershell module. Those of course will only work on a local windows box but I'm sure the x-plat azure CLI tools have a comparable command.

**Comment by sneal** [comment]
Closing, this seems to be an issue with the environment.
