### ISSUE TITLE
 Any plans to release 1.3.5 for UTF-8 support for Vagrant?

### ISSUE THREAD

**Issue by StefanScherer** [WinRb/WinRM#157]
As Hashicorp puts in all efforts to polish the new Vagrant version 1.8 I remembered of this module and the 1.3.5.dev version which supports UTF-8 as default codepage.

So should this gem be released before so Vagrant 1.8 can also support NanoServer, Win2016TP4 ... better ?

Further reading ;-) http://www.hurryupandwait.io/blog/a-packer-template-for-windows-nano-server-weighing-300mb

Ping @mitchellh @sethvargo

**Comment by mwrock** [comment]
I think a 1.3.5 release would be fine. 

On a related note, Windows server 2016 TP4 shipped today with some new nano bits. Can't wait to build an updated nano box to see what has changed.

**Comment by StefanScherer** [comment]
Yeah, I got my Win2016TP4 packer up-to-date, but I also want to install Windows Docker in it in a packer build run, currently retrying...

**Comment by StefanScherer** [comment]
Microsoft has super easy URL shortener for TP4 ;-) 
ISO download link: https://aka.ms/tp4/serveriso
md5 sum: 935ba77651210bd1bd71a114c92b0caa

**Comment by mwrock** [comment]
v1.3.5 is released. Will try to get a PR into vagrant later today to pull in this version.

**Comment by StefanScherer** [comment]
Great! Thanks. I hope this gets into Vagrant 1.8 :+1:

**Comment by mwrock** [comment]
Taking a quick look at https://github.com/mitchellh/vagrant-installers/blob/master/package/package.ps1, looks like the vagrant installer build will grab gems based on the constraints of the vagrant gemspec at build time so this version should make it in to the next build.

@mitchellh @sethvargo: let me know if thats not right. Thanks!

**Comment by StefanScherer** [comment]
@mwrock I think so that the [vagrant.gemspec](https://github.com/mitchellh/vagrant/blob/master/vagrant.gemspec#L31-L32) is used to
I once updated it for a Win10 problem: https://github.com/mitchellh/vagrant/commit/73a7b1d11ebfcb844f5532dddcbad90886d93ef6

But having a look at it now this line should also be updated to use winrm-fs 0.2.3. What do you think?

**Comment by StefanScherer** [comment]
@mwrock the new winrm gem 1.3.5 works perfectly.
I just downloaded your new NanoServer and updated my "vagrant plugin" to use winrm 1.3.5 in Vagrant 1.7.4:

```
$ vagrant plugin list
winrm (1.3.4)
winrm-fs (0.2.2)
vagrant-hostmanager (1.6.1)
vagrant-multiprovider-snap (0.0.14)
vagrant-pristine (0.3.0)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.2)
vagrant-vmware-fusion (4.0.1)
~
$ vagrant plugin install winrm
Installing the 'winrm' plugin. This can take a few minutes...
Installed the plugin 'winrm (1.3.5)'!
~
$ vagrant plugin list
winrm (1.3.5)
winrm-fs (0.2.3)
vagrant-hostmanager (1.6.1)
vagrant-multiprovider-snap (0.0.14)
vagrant-pristine (0.3.0)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.2)
vagrant-vmware-fusion (4.0.2)
```

I can't wait to use `vagrant powershell`

**Comment by sneal** [comment]
This is great to see! Especially the part about me not being a SPOF. Thanks guys.
