### ISSUE TITLE
Any way to get VERSION internally?

### ISSUE THREAD

**Issue by djberg96** [WinRb/WinRM#164]
I'm fighting with Bundler on a project a bit, and I didn't see a way to get the WinRM version internally to verify which version I'm using.

I see that you have a VERSION file internally, but it looks like it's only being used by the gemspec. I think the typical approach these days is to put that under lib as version.rb, and then refer to that file for both the gemspec and the library itself.

Then I can check WinRM::VERSION in my debugging code. :)

Unless there's some way to get at it and I've missed it.

**Comment by sneal** [comment]
You're correct its only available in the gemspec. Making the version available at runtime makes sense to me.

**Comment by sneal** [comment]
Fixed by #165
