### ISSUE TITLE
WinRM and Kerberos

### ISSUE THREAD

**Issue by sdeshpande** [WinRb/WinRM#166]
Hello Guys,
Can you please guide me in setting up WinRB to work with Kerberos authentication. I am able to get it work with Basic and Unencrypted authentication. But I really need to have Kerberos authentication for production infrastructure. 
Really appreciate all your help. 
Regards,
Saurabh

**Comment by sdeshpande** [comment]
Can someone please assist ?

**Comment by sneal** [comment]
You can use the Kerberos library supported by the OS where you're running this gem. You should validate you have the library properly configured using its own procedures and tools.

Once you have that working then simply instantiate a WinRM service object as in the readme:

```ruby
winrm = WinRM::WinRMWebService.new('http://mywinrmhost:5985/wsman', :kerberos, :realm => 'example.com')
```

**Comment by sdeshpande** [comment]
It would be really helpful if you can guide me in the right direction for getting Kerberos to work. Really appreciate any help you can provide.

**Comment by aytch** [comment]
Have you followed the instructions for winrm over https as outlined here: https://support.microsoft.com/en-us/kb/2019527 ?

I haven't had any success in my environment with getting this working on https/5986, but I haven't had much time to devote to researching the issue.

I don't think this is an issue with the winrm gem, but rather an issue with the complexities of secured environments and how they communicate - my apologies to anyone if there is a better method for communicating other than github, and I'm simply unaware of it.

Kerb authentication works fine over http/5985, but the https portion I haven't solved.

**Comment by sdeshpande** [comment]
Thanks a lot. I will give this a try.
