### ISSUE TITLE
Windows XP doesn't execute scripts via winrm after 1.3.4

### ISSUE THREAD

**Issue by jamusj** [WinRb/WinRM#173]
I've tracked down an odd issue with winrm and windows XP.

Starting with 1.3.5, it seems like it doesn't execute external scripts.  

To make sure it wasn't just an error capturing stdout, I also tested with a script that updated "c:\test.out", and with 1.3.5, it didn't create the file, and with 1.3.4, it did.

This was originally reported via https://github.com/mitchellh/vagrant/issues/6839, but since I was able to create a simple winrm script that reproduces the problem I'm creating a ticket here.

Below is the test scripts I was using and the outputs.  

test.rb:
```
require 'winrm'
endpoint = 'http://localhost:55985/wsman'
myuser="IEUser"
mypass="Passw0rd!"
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => myuser, :pass => mypass, :basic_auth_only => true )

STDOUT.print "====================\n"
STDOUT.print "via test.cmd:\n"
winrm.cmd('c:\\test.cmd') do |stdout, stderr|
  STDOUT.print stdout
  STDERR.print stderr
end

STDOUT.print "\n====================\n"
STDOUT.print "via echo:\n"
winrm.cmd('echo Hello world!') do |stdout, stderr|
  STDOUT.print stdout
  STDERR.print stderr
end

STDOUT.print "====================\n"
```

test.cmd
```
echo Hello world!
```

On 1.3.4:
```
====================
via test.cmd:

C:\Documents and Settings\IEUser>echo Hello World! 
Hello World!

====================
via echo:
Hello world!
====================
```

On 1.3.5:
```
====================
via test.cmd:

====================
via echo:
Hello world!
====================
```

**Comment by sneal** [comment]
Based on the information provided I would wager XP doesn't like [the code page change to 65001](https://github.com/WinRb/WinRM/compare/v1.3.4...v1.3.5).

**Comment by mwrock** [comment]
Yeah. We never tested below 2k8R2 for the UTF-8 switch. I agree with @sneal's comment at https://github.com/mitchellh/vagrant/issues/6839 that losing support for XP would be a bummer (did I just really say that??). I think it would be straight forward to add a conditional to the codepage and make 65001 the default only if the windows version is less than win 7/2k8r2. Now that the `CommandExecutor` sniffs the version, that should be doable.
