### ISSUE TITLE
Bat files always return empty stdout,stderr and return code 0

### ISSUE THREAD

**Issue by jfhutchi** [WinRb/WinRM#181]
I'm attempting to execute bat files specifically the knife.bat(via direct call or the knife command) in Chef-client 12.4.1 on Windows Server 2008 SP2 via CommandExecutor.run_cmd 'C:\opscode\chef\bin\knife.bat' this should return an error because that is not the full command with parameters. I've also tested a bat file that simply does the dir command again this works on the machine via command prompt but not via CommandExecutor...has something changed recently that would cause this? I have tested doing the same thing on windows 2012 and it works fine.

**Comment by mwrock** [comment]
Having a tough time reproducing:

I am assuming that you mean 2008R2 and not SP2?

I created a c:/test.bat file on a windows 2008R2 VM with this content:
```
echo yo
exit 5
```

Then in an irb session running:
```
require 'winrm'
winrm = WinRM::WinRMWebService.new('http://192.168.137.765:5985/wsman', :negotiate, :user => 'vagrant', :pass => 'vagrant)
ex = winrm.create_executor
ex.run_cmd('c:/test.bat')
```

This returns:
```
=> {:data=>[{:stdout=>"\r\n"}, {:stdout=>"C:\\Users\\Administrator>echo yo \r\nyo\r\n\r\nC:\\Users\\Administrator>exit 5 \r\n"}], :exitcode=>5}
```

Do these steps deviate much from what you are doing?

**Comment by jfhutchi** [comment]
it is the same as what I'm doing 
here is some of the system info output..
Microsoft Windows Server 2008 Standard
6.0.6002 Service Pack 2 Build 6002

**Comment by mwrock** [comment]
Oh ok. Yeah not R2. Will need to find a 2008 vm to troubleshoot. Can you try reverting to v1.3.4 and see if you get the same results?

**Comment by jfhutchi** [comment]
is 1.3.4 the last "Stable"? I was using 1.5 before.

**Comment by mwrock** [comment]
well i'm wondering if this is at all related to the codepage change in 1.3.5 really, but yeah 1.6.0 is possible too. gonna mosey on over to MSDN tonight and get me some pre R2 2008

**Comment by mwrock** [comment]
probably does not matterbut you running 64 or 32 bit? That was the last server OS that had both.

**Comment by jfhutchi** [comment]
64bit

**Comment by mwrock** [comment]
Reproduced this and its actually the exact same problem as #173. I'm now gonna start working on a fix to address both.
