### ISSUE TITLE
get_command_output fails on invalid utf-8 data in stream

### ISSUE THREAD

**Issue by saw792** [WinRb/WinRM#184]
In Ruby 2.1 and below the following line in winrm_service.rb:get_command_output can produce an 'ArgumentError: invalid byte sequence in UTF-8' if the output text includes binary components. The line of code in question (256):

```ruby
# decode and strip off BOM which win 2008R2 applies
stream = { n.attributes['Name'].to_sym => Base64.decode64(n.text).force_encoding('utf-8').sub("\xEF\xBB\xBF", "") }

```
Specifically the call to 'sub' validates the decoded text and throws the exception.

In the absence of any way to enforce valid utf-8 formatted command output can we please strip out invalid characters before calling 'sub' to replace the BOM?

Proposed change (for Ruby 2.1+):

```ruby
# decode and strip off BOM which win 2008R2 applies
stream = { n.attributes['Name'].to_sym => Base64.decode64(n.text).force_encoding('utf-8').scrub.sub("\xEF\xBB\xBF", "") }
```

Proposed change (to not break backwards compatibility):

```ruby
# decode and strip off BOM which win 2008R2 applies
decoded_text = Base64.decode64(n.text).force_encoding('utf-8')
if ! decoded_text.valid_encoding?
  decoded_text = decoded_text.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('utf-8')
end
stream = { n.attributes['Name'].to_sym => decoded_text.sub("\xEF\xBB\xBF", "") }
```

**Comment by mwrock** [comment]
closed via #185
