### ISSUE TITLE
command executor os_version comparison is incorrect

### ISSUE THREAD

**Issue by sneal** [WinRb/WinRM#189]
The CommandExecutor OS version checking is comparing strings and not numbers.

```
'6.2' < '6.3'
=> true
 '6.1' < '6.3'
=> true
'10' < '6.3'
=> true
```

Obviously 10 should not be less than 6.3, however since we're doing a character comparison and not a number comparison...

**Comment by mwrock** [comment]
ugh. Nice find. If you give #190 a quick +1 I'll release.

**Comment by sneal** [comment]
I'm just disappointed I didn't find it in the original PR. It was only when I was working in the code all day yesterday that I noticed it those were strings.

**Comment by mwrock** [comment]
Heh. disappointments all around here, as the one who submited it :)
