### ISSUE TITLE
WinRM::CommandExecutor assumes 1500 operations are allowed per connection

### ISSUE THREAD

**Issue by jerryk55** [WinRb/WinRM#197]
WinRM::CommandExecutor.max_commands assumes that 1500 commands may be executed in one remote shell session, and resets the shell session when 1498 commands have been executed.  The value 1500 is the default WinRM MaxConcurrentOperationsPerUser value.  This value can be modified by an Administrator and consequently gem may hit the max operations limit well before it reaches 1500.

One fix for this issue would be to actually fetch the value from the server and use said value to determine when to restart the remote shell session.

**Comment by mwrock** [comment]
Unfortunately fetching the value over WinRM fails on Windows 2008 R2/win 7 and below. Another approach that I plan on implementing in WinRM v2, Is to not count at all but instead simply reset the connection when we get the WSMan Fault thet too many commands have been run. That should deal with tweaked settings and eliminates the need to do any OS check.

**Comment by jerryk55** [comment]
That works as well.  👍

**Comment by mwrock** [comment]
I believe this can be closed now after #191 since we now reset the connection specifically when the connection reaches its limit.
