### ISSUE TITLE
Unable to use initialize a connection using :negotiate with WinRM 1.7.3

### ISSUE THREAD

**Issue by aalblas** [WinRb/WinRM#198]
I am trying to use the negotiate method for connecting to a remote Windows host from a Linux Host (Centos 6.7)

winrm = WinRM::WinRMWebService.new(endpoint, :negotiate, :user => myuser, :pass => mypass)

This fails with:

/usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/encode_util.rb:42:in `encode_utf16le': undefined method `encoding' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client/session.rb:187:in `oem_or_unicode_str'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client/session.rb:172:in `password'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client/session.rb:192:in `ntlmv2_hash'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client/session.rb:196:in `calculate_user_session_key!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client/session.rb:27:in `authenticate!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rubyntlm-0.6.0/lib/net/ntlm/client.rb:36:in `init_context'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/transport.rb:228:in `init_auth'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/transport.rb:166:in `send_request'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/winrm_service.rb:489:in `send_message'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/winrm_service.rb:390:in `run_wql'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/command_executor.rb:186:in `os_version'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/command_executor.rb:145:in `code_page'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/command_executor.rb:72:in `block in open'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/command_executor.rb:218:in `retryable'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/command_executor.rb:71:in `open'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/winrm_service.rb:356:in `create_executor'

If I change to :kerberos it works fine. 

Has anyone else had this issue?

WinRM 1.7.3
Rubyntlm 0.6.0

**Comment by mwrock** [comment]
we totally need better error handling here, but this means you passed a nil password.

**Comment by aalblas** [comment]
Thanks for the quick response.

I misspelled ':pass' ...sorry

A better error would be nice but this was user error on my part.

It's working now :)
