### ISSUE TITLE
Question: Client Certificate-based Authentication (password-less)

### ISSUE THREAD

**Issue by elpetak** [WinRb/WinRM#199]
Is WinRM certificate-based (password-less) authentication supported?

Thanks!

Official doc: https://msdn.microsoft.com/en-us/library/windows/desktop/aa384295%28v=vs.85%29.aspx
An example: https://cloudbase.it/windows-without-passwords-in-openstack/

**Comment by mwrock** [comment]
Currently the WinRM gem only supports password based authentication. Its certainly possible to implement.

**Comment by elpetak** [comment]
Looks like there is a python implementation that has it... I'll see if I can make that work in Ruby :-)
https://github.com/diyan/pywinrm/blob/master/winrm/transport.py

**Comment by elpetak** [comment]
Good news, I've done a couple of tests and it works (provided the right headers are sent).

Open question:

To make cert-based auth work we only need to do 2 things on the Gem side:
    1. Send this header in the requests: 'Authorization' => 'http://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/https/mutual'
    2. Add the client cert/key pair to httpcli.ssl_config

The question is about how to implement that.
I was thinking making a new class, similar to BasicAuthSSL but maybe called ClientCertAuthSSL (?) that loads the client cert/key pair (from either files or strings) instead of setting user/password, and then modify the HTTPTransport#send_request method to include the required header when a client cert/key pair is present.
That would be the easiest, but I'm open to suggestions.

**Comment by mwrock** [comment]
That sounds like a reasonable approach. The options could include a `certificate` and if it resolves to an existing file, then read the key from the file otherwise assume the sting is the cert.

**Comment by jfhutchi** [comment]
@elpetak  and I submitted a pull request yesterday with a way to achieve the password-less cert-based authentication. Let us know what you think of it.

**Comment by jfhutchi** [comment]
I think this can be closed
