### ISSUE TITLE
uninitialized constant WinRM::HTTP::HttpNegotiate::WinRMWebServiceError

### ISSUE THREAD

**Issue by djberg96** [WinRb/WinRM#203]
Due to some odd circumstances where I'm trying to use this in conjunction with some VCR cassettes, I hit this error:

    uninitialized constant WinRM::HTTP::HttpNegotiate::WinRMWebServiceError

It's coming from https://github.com/WinRb/WinRM/blob/master/lib/winrm/http/transport.rb#L218

But I don't see it defined in exceptions.rb. I'm assume that it should be defined, or that it's supposed to raise a different error.

**Comment by mwrock** [comment]
Yeah it should be. However even if we fix it (which we should) the fact that you are getting to that line indicates something deeper is wrong and the message cant be decrypted or atleast rubyntlm cannot verify the decryption. Is there something that might be "hijacking" the messages?

**Comment by djberg96** [comment]
Yep, there's definitely some other problem, but I haven't nailed it down yet. Something to do with VCR I think, but I'm not positive.

**Comment by majkinetor** [comment]
I have this using vagrant: https://github.com/mitchellh/vagrant/issues/7446

**Comment by djberg96** [comment]
Looks like this was fixed in v2, closing.
