### ISSUE TITLE
Question: Do we have an interactive mode similar to SSH?

### ISSUE THREAD

**Issue by jfhutchi** [WinRb/WinRM#207]
Using SSH to execute my chef-clients (which are configured to write to logs) I am still able to get the console information in stdout using interactive mode. Currently I'm not able to do this on my Windows Servers. Is there an interactive flag I'm not seeing?

**Comment by mwrock** [comment]
Might have a look at this thread: https://discourse.chef.io/t/knife-winrm-does-not-show-output-after-joining-domain/8132/5

My guess is you have a `log_location` in your client.rb that is suppressing the console. To quote that thread:

> This will not only cause chef run output to log to that location but will suppress output to STDOUT unless in a tty. One unfortunate characteristic of a WinRM session is that it is NOT associated with a TTY in a console like SSH. So the checks that chef performs thinks that you are running in a headless mode.
> 
> You can get around this by removing the log location from your client.rb or you can create an alternate client.rb and use the -c argument of chef-client to point to it.
> 
> That feels like a pretty lame workaround so you may consider opening an issue regarding this on the chef repo.
>

**Comment by jfhutchi** [comment]
Thanks Matt!
