### ISSUE TITLE
Block in 'ffi_lib' Could not open library gssapi32.dll

### ISSUE THREAD

**Issue by BentleyTrevorA** [WinRb/WinRM#209]
So I am running WIndows 7 and have installed winrm using 'gem install -r winrm' and have modifed the example script to match my endpoint and krb5_realm, and when I run it, and I get the following error which I can't seem to be able to find a solution for:

C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'C:\Program Files (x86)\MIT\Kerberos\bin\gssapi32.dll': c (LoadError)
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi/lib_gssapi_loader.rb:31:in `load_mit'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi/lib_gssapi_loader.rb:70:in `<module:LibGSSAPI>'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi/lib_gssapi_loader.rb:7:in `<module:GSSAPI>'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi/lib_gssapi_loader.rb:6:in `<top (required)>'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi/lib_gssapi.rb:6:in `<top (required)>'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/gssapi-1.2.0/lib/gssapi.rb:17:in `<top (required)>'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/winrm-1.8.0/lib/winrm/winrm_service.rb:63:in `init_kerberos_transport'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/winrm-1.8.0/lib/winrm/winrm_service.rb:52:in `initialize'
        from Test-SSL.rb:4:in `new'
        from Test-SSL.rb:4:in `<main>'

I have Kerberos MIT 64 and 32 bit installed so C:\Program Files (x86)\MIT\Kerberos\bin\gssapi32.dll exists and should be accessible. Not sure why it's saying it can't open it.

Is there some other dependency I'm missing? Or something else I need to do to get this to work?

Example Script Used:
require 'winrm'
endpoint = 'http://mywinrmhost:5985/wsman'
krb5_realm = 'EXAMPLE.COM'
winrm = WinRM::WinRMWebService.new(endpoint, :kerberos, :realm => krb5_realm)
winrm.create_executor do |executor|
  executor.run_cmd('ipconfig /all') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
end

**Comment by sneal** [comment]
I'm guessing this also fails: `require 'gssapi'`?

**Comment by BentleyTrevorA** [comment]
Yeah it produces the same error

**Comment by BentleyTrevorA** [comment]
I uninstalled ruby (x64) and installed 32 bit ruby and I no longer have this issue. Looks like it was in 64 bit only.
