### ISSUE TITLE
CredSSP support for preventing the double hop problem?

### ISSUE THREAD

**Issue by dvucko** [WinRb/WinRM#212]
Is there any way to use CredSSP with WinRb/WinRM in order to avoid the double hop authentication problem? For example, when trying to manage SharePoint remotely, CredSSP authentication is required to be able to authenticate not only to the WSMan service (first hop), but to the SharePoint itself (second hop - problematic by default). Details: [https://blogs.msdn.microsoft.com/besidethepoint/2010/05/26/powershell-remoting-for-sharepoint/](https://blogs.msdn.microsoft.com/besidethepoint/2010/05/26/powershell-remoting-for-sharepoint/)

**Comment by jerryk55** [comment]
@dvucko have you looked at winrm-elevated?  It has solved the double hop authentication problem for the use cases I have in my environment.  Your mileage may vary.

**Comment by dvucko** [comment]
@jerryk55 I should've seen this earlier - thank you, I will try it and see if it works.

**Comment by mwrock** [comment]
Yup. winrm-elevated is likely what you want. There is currently no ruby implementation of CredSSP authentication.
