### ISSUE TITLE
winrm-authentication-protocol negotiate

### ISSUE THREAD

**Issue by ch3k1** [WinRb/WinRM#216]
hi 
i got this error:

WARNING: You are using '--winrm-authentication-protocol negotiate' with 
'--winrm-transport plaintext' on a non-Windows system which results in
unencrypted traffic. To avoid this warning and secure communication,
use '--winrm-transport ssl' instead of the plaintext transport,
or execute this command from a Windows system which enables encrypted
communication over plaintext with the negotiate authentication protocol.

any solutions?

**Comment by mwrock** [comment]
This looks like knife-windows. I think this issue will be better discussed there and I'll be happy to respond there. When posting please specify the version of knife-windows you are using. Thanks!
