### ISSUE TITLE
Invalid transport 'negotiate' specified, expected: negotiate, kerberos, plaintext, ssl.

### ISSUE THREAD

**Issue by sneal** [WinRb/WinRM#217]
Running test-kitchen in AppVeyor and getting this error.

```
c:\opscode\chefdk\bin\kitchen verify
-----> Starting Kitchen (v1.11.1)
-----> Creating <tasks-windows-2012R2>...
       Resetting instance state with command: exit 0
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Invalid transport 'negotiate' specified, expected: negotiate, kerberos, plaintext, ssl.] on tasks-windows-2012R2
```

Guess - might be 'negotiate' versus :negotiate. At the very least this isn't very user friendly.

**Comment by mwrock** [comment]
Interesting, even a symbol should be converted to a string in the interpolation:
```
send "init_#{transport}_transport", opts.merge({endpoint: endpoint})
``` 
Can you run test-kitchen with with `-l debug`? Maybe the `error is originating further down in `HTTPNegotiate`. Also just curious, are you explicitly setting the transport type in the kitchen.yml? It defaults to negotiate but perhaps something goes wrong wen it is explicitly set to `negotiate`.

**Comment by sneal** [comment]
Definitely a misleading error. I was attempting to setup a [cookbook build in AppVeyor](https://ci.appveyor.com/project/ChefWindowsCookbooks65871/visualstudio/build/master-25) and used the wrong env vars to pass along the winrm username and password so the username and password got passed as nil:

```
negotiate::http://localhost:5985/wsman<{:user=>nil, :pass=>nil, :elevated_username=>nil, :elevated_password=>nil, :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}> (exit 0)
```

**Comment by mwrock** [comment]
I was not able to reproduce this issue @sneal but i did add better error handling to v2 explicitly validating the transport type instead of rescuing `NoMethodError`.

**Comment by sneal** [comment]
Nice, and if it fails for a different reason now we'll get a proper stack trace.
