### ISSUE TITLE
Error stream parsing

### ISSUE THREAD

**Issue by chris-rock** [WinRb/WinRM#220]
Awesome project! We are using it heavily in InSpec and I would like to implement the following for Windows and InSpec:

```
# test stderr
describe powershell("Write-Error \"error\"") do
  its('stdout') { should eq '' }
  # this is an xml error for now, if the script is run via WinRM
  # @see https://github.com/WinRb/WinRM/issues/106
  # its('stderr') { should eq 'error' }
end
```

Since the error message is not parsed, I get the following error:

```
 Powershell stdout
     ✔  should eq ""
     ✖  should eq "error"\n
     expected: "error"
          got: "Write-Error \"error\" : error\n    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException\n    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException\n"
     
     (compared using ==)
     
     Diff:
     @@ -1,2 +1,4 @@
     -error
     +Write-Error "error" : error
     +    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     +    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

Do you have any good idea, how we can improve that?

**Comment by mwrock** [comment]
There was alot of work in winrm v2 to make powershell stderr MUCH better. For example, on v2 the above stderr would now be:
```
irb(main):009:0> puts shell.run("write-error 'error'").stderr
write-error 'error' : error
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
=> nil
irb(main):010:0>
```
So no more crazy XML output.

**Comment by mwrock** [comment]
We tried to make stderr the same as what you would see in straight up powershell. We may have missed some edge cases so please file issues if you see unexpected results.

Definitely try out https://github.com/chef/train/pull/122 against inspec and see if that produces the desired output for the above spec.

**Comment by chris-rock** [comment]
I currently run the InSpec integration tests https://github.com/chef/inspec/pull/1018 with chef/train#122

**Comment by mwrock** [comment]
Oh I should have included this too:
```
irb(main):010:0> puts shell.run("write-error 'error'").stdout

=> nil
```
So stdout is now empty.

**Comment by chris-rock** [comment]
@mwrock stdout is no issue. I was only discussing about `stderr`

**Comment by mwrock** [comment]
oh ok. Are these specs in inpec? I can take a look.

**Comment by chris-rock** [comment]
Those are included in https://github.com/chef/inspec/blob/master/test/integration/default/powershell_spec.rb#L38-L41. To test it, you would need the https://github.com/chef/inspec/pull/1018

**Comment by mwrock** [comment]
cool. will have a look now

**Comment by mwrock** [comment]
I should have read the spec above more closely. So it sounds like what you are looking for is to have stderr equal the message spit out from `write-error`. Currently, the `WinRM::Output` returned from `run` will return stderr matching what powershell would return. To get just `error`, you'd really need to do something like:
```
write-error 'error'
$err = $Error[0]
write-output $err.Exception.message
```
Then you'd see err from `stdout`

**Comment by chris-rock** [comment]
@mwrock Alright. Got you. I'll update the integration tests to expect the full error string.

**Comment by mwrock** [comment]
The `:powershell` shell does expose a `send_pipeline_command` which is so far undocumented. It returns an array of low level PSRP response messages that could be parsed for the specific error message.

**Comment by mwrock** [comment]
I think you could find the message that hase a `type` of `WinRM::PSRP::Message::MESSAGE_TYPES[:error_record]` and then look at `message.parsed_data.exception[:message]`
