### ISSUE TITLE
WinRMWebService class removed in earlier commit?

### ISSUE THREAD

**Issue by NickMRamirez** [WinRb/WinRM#228]
The WinRM::WinRMWebService class (lib/winrm/winrm_service.rb) was removed in this commit: https://github.com/WinRb/WinRM/commit/e616353aef531ff8a2cee976f7068685a084a22a

This was being used by the ServerSpec library for Windows, https://github.com/mizzy/serverspec/blob/master/WINDOWS_SUPPORT.md. It uses WinRM as in the following:

```
winrm = ::WinRM::WinRMWebService.new(endpoint, :ssl, :user => user, :pass => pass, :basic_auth_only => true)
```

Has this class been replaced? I see in the README that the example is:

```
opts = { 
  endpoint: 'http://myhost:5985/wsman',
  user: 'administrator',
  password: 'Pass@word1'
}
conn = WinRM::Connection.new(opts)
```

**Comment by sneal** [comment]
@NickMRamirez You're correct, in WinRM gem version 2.0 the WinRM::WinRMWebService class was removed and has been superseded by the WinRM::Connection class. You can either constrain the WinRM gem to < 2.0 for your needs or make the necessary change to support WinRM gem v2.
