### ISSUE TITLE
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/http/transport.rb:208:in `winrm_decrypt': Could not decrypt NTLM message. (). (WinRM::WinRMHTTPTransportError)

### ISSUE THREAD

**Issue by rayterrill** [WinRb/WinRM#235]
Stack trace:

`DEBUG: [WinRM] Waiting for output...
DEBUG: [WinRM] cleaning up command_id: 1620B3BF-318B-4D47-9AB9-FB158EA2B665 on shell_id 93CB3B1D-3483-4E1C-8513-444C58C29388
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/http/transport.rb:208:in `winrm_decrypt': Could not decrypt NTLM message. (). (WinRM::WinRMHTTPTransportError)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/http/transport.rb:184:in `send_request'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/wsmv/receive_response_reader.rb:95:in `send_get_output_message'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/wsmv/receive_response_reader.rb:63:in `read_response'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/wsmv/receive_response_reader.rb:47:in `block in read_output'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/wsmv/receive_response_reader.rb:75:in `with_output'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/wsmv/receive_response_reader.rb:46:in `read_output'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/shells/base.rb:76:in `block in run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/shells/base.rb:122:in `with_command_shell'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/shells/base.rb:75:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_session.rb:68:in `block in relay_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.0.2/lib/winrm/connection.rb:42:in `shell'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_session.rb:66:in `relay_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_knife_base.rb:130:in `block in relay_winrm_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_knife_base.rb:128:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_knife_base.rb:128:in `relay_winrm_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm_knife_base.rb:114:in `run_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm.rb:60:in `execute_remote_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-windows-1.6.0/lib/chef/knife/winrm.rb:52:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:430:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:429:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/embedded/bin/knife:22:in `load'
        from C:/opscode/chefdk/embedded/bin/knife:22:in `<main>'`

This originally happened on a new machine. Circled back around and validated that it's happening on my existing machines as well.

Upgrade to ChefDK 0.18.26, no dice. No other changes that I'm aware of on the ChefDK/Client side. I'm sure Windows patches have been applied. Able to reproduce/troubleshoot/provide more detail as needed. Thanks.

**Comment by rayterrill** [comment]
Gah - Just double and tripled checked some stuff, and my knife.rb had some leftover proxy stuff in there for downloading cookbooks from Supermarket. My bad. :(

**Comment by mwrock** [comment]
Yeah stuff like this has come up a number of times and its just so easy for proxy related stuff to get set somewhere and make this all extremely hard to debug. I'm think we should always include all/any proxy variable and their values in the debug output to make proxy settings more obvious.

**Comment by rayterrill** [comment]
I guess my n00b question would be for WinRM, why is the proxy stuff even coming into play? I mean that's typically 5985/6 versus 80/443 - why even take the proxy into account for WinRM?

**Comment by mwrock** [comment]
Oh if only winrm were free from proxies. Many Enterprises require winrm traffic, which is HTTP, to go through a proxy server. So ensuring HTTP_PROXY variables are properly set is important in those environments in order to connect.

**Comment by rayterrill** [comment]
Wow and I thought our enterprise was restrictive with proxy stuff. :)

Maybe a switch to say "ignore proxy settings for WinRM traffic"? Right now I end up commenting/uncommenting things in my knife.rb when I need the proxy or not. And occasionally forget how I had it last, and thus report bugs that are user error.

**Comment by Cloudenablement** [comment]
Can anyone please post clearly how this error can be resolved?
