### ISSUE TITLE
WinRM does not work with Windows Server 2016 WinRM::WinRMAuthorizationError

### ISSUE THREAD

**Issue by ITD27M01** [WinRb/WinRM#239]
After upgrade to W2k16 from W2K12R2 winrm no longer work - I always get WinRM::WinRMAuthorizationError.
I try to use ssl and negotiate with 1.7.3 and 2.1.0 version. I tested similar configuration on a nearby server W2k12. It works.

**Comment by mwrock** [comment]
There are many factors that can influence this. Are you using a domain or local account? If using a local account, make sure you set `LocalAccountTokenFilterPolicy`at `HKEY_LOCAL_MACHINE\software\Microsoft\Windows\CurrentVersion\Policies\system` to `1`.

**Comment by ITD27M01** [comment]
Hi, I apologize for the delay. After a clean install of W2K12 everything worked as it should. Everything is OK.
