### ISSUE TITLE
shell.run not working with ruby 1.9.3

### ISSUE THREAD

**Issue by PPFerrari** [WinRb/WinRM#240]
Hi, 

I'm trying to use WinRM with Ruby 1.9.3, but when I try to run a powershell command it fails with the following error: 

`gems/winrm-2.1.0/lib/winrm/wsmv/base.rb:55:in pack: can't convert Enumerator into Integer (TypeError)`

My code is the following: 

```ruby
conn = WinRM::Connection.new(opts)
conn.shell(:powershell) do |shell| 
  output = shell.run("ipconfig") do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
  puts "The script exited with exit code #{output.exitcode}"
end
```

**Comment by mwrock** [comment]
We no longer suppot 1.9.3 since its been retired for a while. I suppose if we break on 1.9.3 we should state that in our gemspec.

**Comment by PPFerrari** [comment]
Ok, I was trying to use it because at this [page](https://rubygems.org/gems/winrm/versions/2.1.0) the required ruby version is >= 1.9.0.

Thanks for your answer.

**Comment by sneal** [comment]
Fixed
