### ISSUE TITLE
NoMethodError: undefined method `powershell' for #<WinRM::Connection:0x007faae3a517d0>

### ISSUE THREAD

**Issue by stevaaa** [WinRb/WinRM#242]
Hi there, I am trying to execute few spec tests on a windows 2012 server host.
I am unable to figured out what am I doing wrong here. Kindly help! THANKS

Let me know incase you need more information!

**My spec_helper.rb**

require 'serverspec'
require 'winrm'
require 'yarjuf'
require 'yaml'

set :backend, :winrm
set :os, :family => 'windows'

properties = YAML.load_file('properties.yml')
role = "generic"

opts = {
  endpoint: 'http://10.145.28.15:5985/wsman',
  user: 'ChefInstall',
  password: 'P@ssw0rd',
  basic_auth_only: true
}

winrm = WinRM::Connection.new(opts)
Specinfra.configuration.winrm = winrm

RSpec.configure do |c|
  properties[:app_roles][role].each do |filter|
  	c.filter_run_including filter.to_sym
  end
end

**My test file vmtests_spec.rb**

require 'spec_helper'

describe "vmcheck tests", :virtualmachine do
	describe file('c:/Windows') do
		it { should be_directory }
	end
	describe command('ls -al /') do
	  its(:stdout) { should match /bin/ }
	end
end

**Output:**
vmcheck tests
  File "c:/Windows"
    should be directory (FAILED - 1)
  Command "ls -al /"
    stdout
      example at ./spec/tests/vmcheck_spec.rb:8 (FAILED - 2)

Failures:

  1) vmcheck tests File "c:/Windows" should be directory
     Failure/Error: it { should be_directory }
     NoMethodError:
       undefined method `powershell' for #<WinRM::Connection:0x007ffda8ca1900>

      /Library/Ruby/Gems/2.0.0/gems/specinfra-2.61.1/lib/specinfra/backend/winrm.rb:14:in `run_command'
      /Library/Ruby/Gems/2.0.0/gems/specinfra-2.61.1/lib/specinfra/runner.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/specinfra-2.61.1/lib/specinfra/runner.rb:19:in `method_missing'
      /Library/Ruby/Gems/2.0.0/gems/serverspec-2.29.1/lib/serverspec/type/file.rb:26:in `directory?'
      ./spec/tests/vmcheck_spec.rb:5:in `block (3 levels) in <top (required)>'

**Comment by mwrock** [comment]
If Serverspec/specinfra is invoking `powershell` on a connection, its using the v1 api and will not be compatible with a winrm v2 connection.
