### ISSUE TITLE
WinRm rundeck error

### ISSUE THREAD

**Issue by jpjayprasad** [WinRb/WinRM#244]
I am trying to execute power shell commands on windows nodes through rundeck using winrm plugin. The rundeck job runs fine while i specify fqdn of the server as hostname in the rundeck resources xml. But in case if i specify ip address of the server as hostname in the rundeck resources xml, I'm getting the below given error.

[overthere-winrm:xx.xxx.xxx.xxx] failed: WinRM Error: Unexpected HTTP response on http://xx.xxx.xxx.xxx:5985/wsman:   (401)
11:27:47			Failed: WinRMProtocolError: WinRM Error: Unexpected HTTP response on http://xx.xxx.xxx.xxx:5985/wsman:   (401

Is there anything we can do with winrm rundeck plugin to solve this issue.?

**Comment by mwrock** [comment]
Hi there. This is the ruby winrm gem. The rundeck winrm plugin can be found [here](https://github.com/rundeck-plugins/rundeck-winrm-plugin). Hopefully you can find better answers there.
