### ISSUE TITLE
Is an interactive windows id required for this gem?

### ISSUE THREAD

**Issue by jfhutchi** [WinRb/WinRM#250]
Currently hitting some issues when powershell scripts that do not require interactive mode are run via this gem. When we switch the id to interactive the scripts work fine. Is there a config option we should be seeing when calling powershell scripts with this gem?

**Comment by mwrock** [comment]
It really depends on what you are doing in the script. For example, anything that interacts with windows updates whether that be explicitly running windows updates or just installing an MSI that engages with windows updates will fail.

If you really need a local logon, use the winrm-elevated gem which runs everything via a scheduled task.

**Comment by mwrock** [comment]
Definitely feel free to reopen if this does not clarify things for you.
