### ISSUE TITLE
Does the WinRM Gem support FIPS?

### ISSUE THREAD

**Issue by jfhutchi** [WinRb/WinRM#252]
>  WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 1) New-Object : Exception calling ".ctor" with "0" argument(s): "This implementati on is not part of the Windows Platform FIPS validated cryptographic algorithms. " At line:32 char:23 + use ($c = New-Object <<<< -TypeName Security.Cryptography.MD5CryptoService Provider) { + CategoryInfo : InvalidOperation: (:) [New-Object], MethodInvoca tionException + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.Power Shell.Commands.NewObjectCommand

**Comment by jfhutchi** [comment]
I ask this because when I disable FIPS in the registry connections work fine..

**Comment by mwrock** [comment]
This particular gem should be FIPS compliant but the winrm-fs gem has a known issue that is not FIPS friendly. See https://github.com/WinRb/winrm-fs/issues/49
