### ISSUE TITLE
run a batch file

### ISSUE THREAD

**Issue by kmanohar1** [WinRb/WinRM#264]
I have this code:

opts = {
   user: user,
   password: pass,
   endpoint: endpoint,
   operation_timeout: 300,
 }

 conn = WinRM::Connection.new ( opts)
 
 conn.shell(:cmd) do |shell|
  output = shell.run('/var/testwinrm.bat') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
  puts "The script exited with exit code #{output.exitcode}"
end

I basically want to run this batch file '/var/testwinrm.bat'. How do I do that? The above doesn't work

**Comment by mwrock** [comment]
`/var/testwinrm.bat` will fail in a `cmd`shell (remote or local). try `c:\var\testwinrm.bat`.

**Comment by kmanohar1** [comment]
Thank you. It worked.
