### ISSUE TITLE
Question Regarding NTLM/Negotiate 

### ISSUE THREAD

**Issue by jfhutchi** [WinRb/WinRM#280]
I was wondering what level of encryption does NTLM/Negotiate give? 256 bit? Haven't been able to find this searching the web.

**Comment by fwininger** [comment]
I think it's AES-256 Symmetric keys and it's better to use Negociate with an AD (aka Kerberos). NTLM has some weaknesses.

 > https://foxdeploy.com/2017/02/08/is-winrm-secure-or-do-i-need-https/

**Comment by jfhutchi** [comment]
Thank you
