### ISSUE TITLE
winrm escaping the backslash

### ISSUE THREAD

**Issue by srinadhv9** [WinRb/WinRM#295]
When i use the below code, the request going to windows server is missing backslash in the username. 

I have tried using all the different versions of winrm.

Error Log on windows: 
Account For Which Logon Failed:
                Security ID:                            NULL SID
                Account Name:                     DOMAINusername
                Account Domain:                 
 
Failure Information:
                Failure Reason:                      Unknown user name or bad password. 
code:
 require 'winrm'
 require 'winrm-elevated' 
 opts = {
          endpoint: "http://xx.xxx.xxx.xx:5985/wsman",
          user: "DOMAIN\username",
          password: "password",
          disable_sspi: true
      }
	  conn = WinRM::Connection.new(opts)
	   conn.shell(:cmd) do |shell|
        command_output = shell.run("netstat") do |out, err|
          STDOUT.print out
          STDERR.print err          
        end
      end

**Comment by mwrock** [comment]
The `\` is an escape character in ruby. Try either using single quotes instead or a double backslash `\\`.
