### ISSUE TITLE
lib/winrm/psrp/powershell_output_decoder.rb uses windows line endings which make rdoc fail

### ISSUE THREAD

**Issue by dcermak** [WinRb/WinRM#299]
The file `lib/winrm/psrp/powershell_output_decoder.rb` uses windows line endings. These make `rdoc` fail which is used by default when creating an rpm package on OpenSUSE. 

Could you please change this to unix line endings or would you accept a pull request changing this?

**Comment by MuhammetDilmac** [comment]
Try `gem install -r winrm --no-document` it's temporarily fix :)

**Comment by dcermak** [comment]
> Try `gem install -r winrm --no-document` it's temporarily fix :)

Yeah, sure, but then the docs don't get installed. We've included a fix in openSUSE for now to modify the line-endings on the problematic file during rpmbuild. It would be nice to have this upstream though.

**Comment by sneal** [comment]
A PR would be great. I would think we could add this to the linting rules to enforce consistent line endings.
