### ISSUE TITLE
Unable to get Kerberos auth working from CentOS against AD

### ISSUE THREAD

**Issue by cwb124** [WinRb/WinRM#54]
I built a CentOS 6.3 box and used the following documentation to add it to our Windows domain:  http://community.spiceworks.com/how_to/show/44885-setup-centos-to-authenticate-via-active-directory

I can successfully log in with my AD creds.  However when I try to use WinRM with kerberos, I am getting the following error:

/app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/http/transport.rb:171:in `+': can't convert nil into String (TypeError)
        from /app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/http/transport.rb:171:in `winrm_encrypt'
        from /app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/http/transport.rb:107:in `send_request'
        from /app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/winrm_service.rb:368:in `send_message'
        from /app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/winrm_service.rb:155:in `get_command_output'
        from /app/interpreters/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/winrm_service.rb:241:in `run_cmd'

Here's the line I am trying to run:   winrm = WinRM::WinRMWebService.new(endpoint, :kerberos, :realm => 'DOMAIN.COMPANY.COM')

I am using the winrm quickconfig although I have tried almost every combination of true/false on the various components.  No matter what I do I can't get around that error.

I can invoke-command successfully from a Windows box to the target Windows server so the box is accepting winrm currently. 

I have successfully used the SSL method to run commands from a CentOS box against Windows and it works great.  But we are looking to implement this across 4000+ Windows servers and would rather not deal with cert enrollment and associated admin issues on that scale.  We want to get kerberos working.  But I'm stuck at this point and not sure how to move forward.

**Comment by sneal** [comment]
Fixed by #109
