### ISSUE TITLE
Handle OperationTimeouts

### ISSUE THREAD

**Issue by seandilda** [WinRb/WinRM#59]
Per http://msdn.microsoft.com/en-us/library/cc251676.aspx:

"If no output is available before the wsman:OperationTimeout expires, the server MUST return a WSManFault with the Code attribute equal to "2150858793". When the client receives this fault, it SHOULD issue another Receive request."

Right now, winrm sees the fault and raises a ruby error.  This means all remote scripts must be crafted to make sure they provide output at least once a minute (winrm uses an OperationTimeout of 60s).  Idealy, winrm would handle the Operation Timeout cleanly.

**Comment by sneal** [comment]
Fixed in 1.3
