### ISSUE TITLE
Mac OSX 10.8

### ISSUE THREAD

**Issue by moserke** [WinRb/WinRM#61]
Anyone been able to get this to work on OSX 10.8?  I have the following configuration...

source os: OSX 10.8.5
targe os: server 2008 R2
winrm: 1.1.3 (modified gemspec to depend on gssapi ~> 1.1)
gssapi: 1.1.2
heimdal: 1.5.3

test code:

```ruby
require 'gssapi/heimdal'
require 'winrm'

winrm = WinRM::WinRMWebService.new("http://box.domain.com:5985/wsman", :kerberos, realm: "DOMAIN.COM")
winrm.powershell('ls')
```

With a modified puts in transport.rb on line 170 the output is:

maj_stat = 851968, min_stat = 22
TypeError: can't convert nil into String
from /Users/x3v7/.rvm/gems/ruby-1.9.3-p194/gems/winrm-1.1.3/lib/winrm/http/transport.rb:177:in `+'

I have been doing a bunch of playing and just can't get this to work.  I also can't find what those error codes (0x000d0000 & 0x00000016 respectively) actually mean.  I have tried digging through the heimdal c code but can't find in their either.

kinit has been done and verified.  If I kdestroy and don't kinit then I can't even create the WinRM::WinRMWebService successfully.

Feels like there is something going on in the gss_wrap_iov function, but without knowing what those return codes are can't troubleshoot any further.

I know that it seems kerberos is being dropped for NTLM but just curious if anyone is in this configuration and have things working.

Have gotten it working from centos, but was hoping to get it working from osx.

**Comment by maxlinc** [comment]
I have been using WinRM on OSX, but I have more recent versions of everything and I haven't been using kerberos.

I'm using:
OSX 10.9
Ruby 2.0 or 2.1
WinRM 1.2 or the 1.3 release candidate

**Comment by sneal** [comment]
It might be possible to get Kerberos working on OS X with this gem, but I wasn't able to. The OS X kerberos libraries are pretty old.
