### ISSUE TITLE
using the repl with powershell

### ISSUE THREAD

**Issue by mwrock** [WinRb/WinRM#99]
I've been playing with the REPL on the v1.3 branch. If you run powershell.exe, it stops processing standard input. I found a sort of hack for this which is to run `powershell -command ^-`. This will process stdin but loses the prompt.

I'm curious if this is a known issue and if anyone else sees the same thing. I thought I may have seen this working a while back but just reverted my local repo and it exhibits the same behavior. I've seen this on both windows and linux hosts.

Unless there is an easy workaround (which I have not found) this may not be worth the effort fixing without taking the plunge to implement the powershell remoting protocol.

**Comment by docwhat** [comment]
For those of us who don't speak powershell, what is `powershell -command ^-`?

**Comment by aytch** [comment]
'^' is an environment variable that contains the last command that ran.

You can view these in Powershell with the command 'gci Variable:'

**Comment by sneal** [comment]
AFAIK the only easy way to make it work with PowerShell is to use the ` -command ^-` syntax. The other approach mentioned of creating a native PowerShell shell is possible, but you have to speak PowerShell Remoting. I spiked this out and was able to actually open a PowerShell shell (without cmd.exe) and run a command, but it was pretty much all hardcoded, the actual protocol would take quite a bit of work.
